// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojrpfllxynkklkfkynwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qcnBmbGx4eW5ra2xrZmt5bnd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NzQ4MzMsImV4cCI6MjA2NDA1MDgzM30.8303lkGMHnEmvpAYfG0yLmBQSMKw5W2Rn_O7dk1TR5A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);